INSERT INTO tb_shelves (capacity, qnt_books, genre) VALUES (0, 0, 'Ficção Científica');
INSERT INTO tb_shelves (capacity, qnt_books, genre) VALUES (0, 0, 'Romance');
INSERT INTO tb_shelves (capacity, qnt_books, genre) VALUES (0, 0, 'Suspense');
INSERT INTO tb_shelves (capacity, qnt_books, genre) VALUES (0, 0, 'Mistério');

INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('Estilhaça-me', 'Tahereh Mafi', 'Ficção Científica', 352, 'Com apenas um toque, Juliette Ferrars é capaz de fazer um homem adulto se ajoelhar de dor e implorar por misericórdia. Um único toque de Juliette pode matar. \nNinguém sabe por que a garota tem um poder tão impressionante, o qual ela acredita ser uma maldição, um fardo que uma pessoa sozinha seria incapaz de carregar. Contudo, o Restabelecimento enxerga essa característica como um dom e passa a vê-la como uma oportunidade uma oportunidade de usá-la como arma letal. Porém, Juliette tem seus próprios planos. \nDepois de passar toda a vida privada de liberdade, ela finalmente está encontrando forças para lutar e para viver um futuro com o garoto que pensava ter perdido para sempre. \nNo eletrizante primeiro volume da série Estilhaça-me, Tahereh Mafi apresenta um mundo distópico hipnotizante, uma emocionante história de super-heróis e uma heroína inesquecível.', 23.99, 'https://m.media-amazon.com/images/I/41VestZBywL._SX339_BO1,204,203,200_.jpg');
INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('Fahrenheit 451', 'Ray Bradbury', 'Ficção Científica', 210, 'Guy Montag é um bombeiro. Sua profissão é atear fogo nos livros. Em um mundo onde as pessoas vivem em função das telas e a literatura está ameaçada de extinção, os livros são objetos proibidos, e seus portadores são considerados criminosos. Montag nunca questionou seu trabalho; vive uma vida comum, cumpre o expediente e retorna ao final do dia para sua esposa e para a rotina do lar. Até que conhece Clarisse, uma jovem de comportamento suspeito, cheia de imaginação e boas histórias. Quando sua esposa entra em colapso mental e Clarisse desaparece, a vida de Montag não poderá mais ser a mesma. \nUm clássico da ficção científica e da literatura distópica, Fahrenheit 451 foi escrito originalmente como um conto: "O bombeiro", contido no volume Prazer em Queimar: histórias de Fahrenheit 451. Incentivado pelo seu editor, transformou a ideia inicial em um romance, que se tornou um dos livros mais influentes de sua geração – e também um dos mais censurados e banidos de todos os tempos. Foi adaptado para o cinema duas vezes, a primeira pelas mãos do lendário cineasta francês François Truffaut, e depois para diversos formatos. \nEscrito durante a era do macartismo – a sistemática censura à arte promovida pelo governo americano nos anos 1950 – Bradbury costumava dizer que a proibição a livros não foi o motivo central que o levou a compor a obra, e sim a percepção de que as pessoas passavam a se interessar cada vez menos pela literatura com o surgimento de novas mídias, como a televisão. Com o passar do tempo, Fahrenheit 451 ganhou muitas camadas de interpretação: a história de um burocrata que questiona a vileza do seu trabalho, o poder libertador da palavra, a estupidez da censura às artes. \nEmbora soubesse estar testemunhando uma transformação social única, Bradbury afirmava não acreditar que o cenário que imaginou se tornaria realidade tão rápido. Lançado em 1953, Fahrenheit 451 é hoje uma obra de leitura indispensável junto com 1984, de George Orwell, e Admirável Mundo Novo, de Aldous Huxley.', 29.28, 'https://m.media-amazon.com/images/I/51tAD0LyZ-L.jpg');
INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('Fundação', 'Isaac Asimov', 'Ficção Científica', 880, 'Obra-prima de Isaac Asimov, a trilogia da Fundação recebeu o histórico prêmio Hugo de Melhor série de ficção científica e fantasia de todos os tempos. \nBaseada no clássico Declínio e queda do Império Romano, de Edward Gibbon, a trilogia sedimentou seu autor como um dos maiores escritores do gênero e influenciou outras mentes geniais, como Carl Sagan, Steven Spielberg, George Lucas, o nobel de economia Paul Krugman, Elon Musk. \nA humanidade está em risco. Uma ciência revolucionária prevê uma longa e inevitável era de trevas e barbárie. Para evitar que isso aconteça, o chamado plano Seldon é colocado em prática ao longo de séculos, e percorre a história da galáxia, prevendo conflitos de nossa civilização. Mas poderá o comportamento humano obedecer a um padrão científico?', 117.99, 'https://editoraaleph.com.br/wp-content/uploads/2021/03/SKU_FundacaoDelux_1.png');
INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('Admirável mundo novo', 'Aldous Leonard Huxley', 'Ficção Científica', 312, 'Em uma sociedade organizada segundo princípios estritamente científicos, Bernard Marx, um psicólogo, sente-se inadequado quando se compara aos outros seres de sua casta. Ao descobrir uma “reserva histórica” que preserva costumes de uma sociedade anterior – muito semelhante à do leitor – Bernard vai perceber as diferenças entre esta civilização e a sua – e a partir de um sentimento de inconformismo ele desafiará o mundo. A história de Bernard se passa em um ambiente em que a literatura, a música e o cinema só têm a função de solidificar a alienação; um universo que louva o avanço da técnica, a produção em série, a uniformidade contra a diversidade. \nMuitas das previsões de Huxley vieram a ser confirmadas anos mais tarde, como a tecnologia reprodutiva, as supostas técnicas de aprendizado durante o sono e a manipulação pelo condicionamento psicológico. \nAo lado de obras como Fahrenheit 451, de Ray Bradbury, e 1984, de George Orwell, que criticavam os governos totalitários de esquerda e de direita, Admirável Mundo Novo figura na lista dos livros mais relevantes e influentes de todos os tempos. O clássico de Huxley não é somente um hábil exercício de futurismo ou de ficção científica, mas um olhar acerca do autoritarismo no mundo desde que o livro foi publicado, em 1932, e que continua a nos assombrar.', 31.00, 'https://m.media-amazon.com/images/I/41IKTYiymKL._SX334_BO1,204,203,200_.jpg');
INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('Duna: Livro 1', 'Frank Herbert', 'Ficção Científica', 680, 'Uma estonteante mistura de aventura e misticismo, ecologia e política, este romance ganhador dos prêmios Hugo e Nebula deu início a uma das mais épicas histórias de toda a ficção científica. Duna é um triunfo da imaginação, que influenciará a literatura para sempre.Esta edição inédita, com introdução de Neil Gaiman, apresenta ao leitor o universo fantástico criado por Herbert e que será adaptado ao cinema por Denis Villeneuve, diretor de A chegada e de Blade Runner 2049.', 48.95, 'https://m.media-amazon.com/images/I/41MRn6hy8-L._SX346_BO1,204,203,200_.jpg');
INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('O instituto', 'Stephen King', 'Ficção Científica', 544, 'No meio da noite, em uma casa no subúrbio de Minneapolis, um grupo de invasores assassina os pais de Luke e sequestra silenciosamente o menino de doze anos. A operação leva menos de dois minutos. \nQuando Luke acorda, ele está no Instituto, em um quarto que parece muito o dele, exceto pelo fato de que não tem janela. E do lado de fora tem outras portas, e atrás delas, outras crianças com talentos especiais, que chegaram àquele lugar do mesmo jeito que Luke. O grupo formado por ele, Kalisha, Nick, George, Iris e o caçula, Avery Dixon, de apenas dez anos, está na Parte da Frente. Outros jovens, Luke descobre, foram levados para a Parte de Trás e nunca mais vistos. \nNessa instituição sinistra, a equipe se dedica impiedosamente a extrair dessas crianças toda a força de seus poderes paranormais. Não existem escrúpulos. Conforme cada nova vítima vai desaparecendo para a Parte de Trás, Luke fica mais e mais desesperado para escapar e procurar ajuda. Mas até hoje ninguém nunca conseguiu fugir do Instituto. \nTão aterrorizante quanto A incendiária e tão espetacular quando It: a Coisa, este novo livro de Stephen King mostra um mundo onde o bem nem sempre vence o mal.', 58.00, 'https://m.media-amazon.com/images/I/4177Wy8Lo5L._SX327_BO1,204,203,200_.jpg');

INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('Os sete maridos de Evelyn Hugo', 'Taylor Jenkins Reid', 'Romance', 360, 'Lendária estrela de Hollywood, Evelyn Hugo sempre esteve sob os holofotes ― seja estrelando uma produção vencedora do Oscar, protagonizando algum escândalo ou aparecendo com um novo marido… pela sétima vez. Agora, prestes a completar oitenta anos e reclusa em seu apartamento no Upper East Side, a famigerada atriz decide contar a própria história ― ou sua “verdadeira história” ―, mas com uma condição: que Monique Grant, jornalista iniciante e até então desconhecida, seja a entrevistadora. Ao embarcar nessa misteriosa empreitada, a jovem repórter começa a se dar conta de que nada é por acaso ― e que suas trajetórias podem estar profunda e irreversivelmente conectadas. \n“Evelyn Hugo faz Elizabeth Taylor parecer sem graça. Você vai rir com ela, chorar, sofrer, e então voltar para a primeira página e fazer tudo de novo.” ― Heather Cocks e Jessica Morgan, autoras de The Royal We', 38.79, 'https://m.media-amazon.com/images/I/41xVhz5sL1L._SX346_BO1,204,203,200_.jpg');
INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('Novembro, 9', 'Colleen Hoover', 'Romance', 352, 'Apesar de ter apenas 18 anos, Fallon já passou por muita coisa. Sobreviveu a um incêndio que a deixou desfigurada, e viu a carreira de atriz desmoronar por conta das cicatrizes. Agora, no aniversário do fatídico acidente, ela finalmente se sente pronta para sair de Los Angeles e recomeçar a vida em Nova York. \nNo almoço de despedida com o pai, bem na véspera da mudança, Fallon conhece Ben, um aspirante a escritor. A atração entre os dois faz com que passem o dia inteiro juntos, mas a partida iminente de Fallon os impede de viver esse amor. Decididos a vencer o destino, fazem uma promessa: se encontrar todo ano nessa mesma data. \nAo longo do tempo, muitas coisas mudam na vida dos dois, mas o ritual dos encontros e sua história de amor viram enredo do livro de Ben. E, quando parece que o destino finalmente conspira para que fiquem juntos, Fallon descobre algo que a faz questionar as motivações do homem por quem está apaixonada. Será que ela não passa de mais uma personagem na trama de Ben?', 31.90, 'https://m.media-amazon.com/images/I/51-A+gK197L._SX320_BO1,204,203,200_.jpg');
INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('A cinco passos de você', 'Rachael Lippincott', 'Romance', 288, 'Stella Grant gosta de estar no controle. Ela parece ser uma adolescente típica, mas em sua rotina há listas de tarefas e inúmeros remédios que ela deve tomar para controlar a fibrose cística, uma doença crônica que impede que seus pulmões funcionem como deveriam. Suas prioridades são manter seus pais felizes e conseguir um transplante – e uma coisa não existe sem a outra. Mas para ganhar pulmões novos, Stella precisa seguir seu tratamento à risca e eliminar qualquer chance de infecção, o que significa que ela não pode ficar a menos que dois metros de distância – ou seis passos – de outros pacientes com a doença. O primeiro item é fácil para ela, mas o segundo pode se provar mais difícil do que ela esperava. \nO único controle que Will Newman deseja é o de sua própria vida. Ele não dá a mínima para o novo tratamento experimental para o qual foi selecionado e não aguenta mais a pressão de sua mãe para que melhore. Prestes a completar dezoito anos, ele mal pode esperar para finalmente se livrar das máquinas e hospitais, usando o pouco de vida que ainda lhe resta para conhecer o mundo. Stella e Will são muito diferentes. Ao mesmo tempo, a doença que os une não é a única coisa que têm em comum. Eles têm que ficar a cinco passos um do outro, mas, conforme a conexão entre os dois aumenta, a vontade de burlar a distância física parece insuportável. Um grande amor vale um passo roubado?', 28.54, 'https://m.media-amazon.com/images/I/4164jpw+6lL._SX326_BO1,204,203,200_.jpg');
INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('Os Dois Morrem no Final', 'Adam Silvera', 'Romance', 416, 'No dia 5 de setembro, pouco depois da meia-noite, Mateo Torrez e Rufus Emeterio recebem uma ligação da Central da Morte. A notícia é devastadora: eles vão morrer naquele mesmo dia. \nOs dois não se conhecem, mas, por motivos diferentes, estão à procura de um amigo com quem compartilhar os últimos momentos, uma conexão verdadeira que ajude a diminuir um pouco a angústia e a solidão que sentem. Por sorte, existe um aplicativo para isso, e é graças a ele que Rufus e Mateo vão se encontrar para uma última grande aventura: viver uma vida inteira em um único dia. \nUma história sensível e emocionante, Os dois morrem no final nos lembra o que significa estar vivo. Com seu olhar único, Adam Silvera mostra que cada segundo importa, e mesmo que não haja vida sem morte, nem amor sem perda, tudo pode mudar em 24 horas.', 44.79, 'https://m.media-amazon.com/images/I/41K6LsoDz9L._SX319_BO1,204,203,200_.jpg');
INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('Teto para dois', 'Beth O’Leary', 'Romance', 400, 'Depois de três meses do fim do seu relacionamento, Tiffy finalmente sai do apartamento do ex-namorado. Agora ela precisa encontrar o quanto antes um lugar barato onde morar. Contrariando os amigos, ela topa um acordo bastante inusitado. \nEnrolado com questões financeiras, Leon tem uma ideia pouco convencional para conseguir dinheiro rápido: anunciar seu apartamento com uma cama só, onde fica apenas no período da manhã, nos dias úteis, já que passa os fins de semana com a namorada e trabalha como enfermeiro no turno da noite. \nSem nunca terem se encontrado pessoalmente, Leon e Tiffy fecham um contrato de seis meses e passam a resolver as trivialidades do dia a dia por Post-its espalhados pela casa. Mas será que essa solução aparentemente perfeita pode resistir a um ex-namorado obsessivo, uma namorada ciumenta, um irmão encrencado, dois empregos exigentes e alguns amigos superprotetores? \nConsiderado “delicioso do início ao fim, uma história de amor encantadora” pela Kirkus Reviews, Teto para doisfoi adaptado para série pela Paramount+ e chega ao Brasil nas próximas semanas. O elenco conta com Jessica Brown Findlay(Uma Beleza Fantástica e Black Mirror) e Anthony Welsh (Masters of None e The Great).', 44.90, 'https://m.media-amazon.com/images/I/51r8wkRUUsL._SX346_BO1,204,203,200_.jpg');
INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('Amor & Gelato', 'Jenna Evans Welch', 'Romance', 320, 'Depois da morte da mãe, Lina fica com a missão de realizar um último pedido: ir até a Itália para conhecer o pai. Do dia para a noite, ela se vê na famosa paisagem da Toscana, morando em uma casa localizada no mesmo terreno de um cemitério memorial de soldados americanos da Segunda Guerra Mundial, com um homem que nunca tinha ouvido falar. Apesar das belezas arquitetônicas, da história da cidade e das comidas maravilhosas, o que Lina mais quer é ir embora correndo dali. \nMas as coisas começam a mudar quando ela recebe um antigo diário da mãe. Nele, a menina embarca em uma misteriosa história de amor, que pode explicar suas próprias origens. No meio desse turbilhão de emoções, Lina ainda conhece Ren e Thomas, dois meninos lindos que vão mexer ainda mais com seu coração. \nUma trajetória que fará Lina descobrir o amor, a si mesma e também aprender a lidar com a perda. Amor & gelato é uma deliciosa viagem pelos mais românticos pontos turísticos italianos, com direito a tudo de mais intenso que o lugar tem a oferecer: desde paixões até corações partidos.', 33.90, 'https://m.media-amazon.com/images/I/41WSqO6wTeL._SX331_BO1,204,203,200_.jpg');

INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('Jogos Vorazes', 'Suzanne Collins', 'Suspense', 400, 'Na abertura dos Jogos Vorazes, a organização não recolhe os corpos dos combatentes caídos e dá tiros de canhão até o final. Cada tiro, um morto. Onze tiros no primeiro dia. Treze jovens restaram, entre eles, Katniss. Para quem os tiros de canhão serão no dia seguinte?... \nApós o fim da América do Norte, uma nova nação chamada Panem surge. Formada por doze distritos, é comandada com mão de ferro pela Capital. Uma das formas com que demonstra seu poder sobre o resto do carente país é com Jogos Vorazes, uma competição anual transmitida ao vivo pela televisão, em que um garoto e uma garota de doze a dezoito anos de cada distrito são selecionados e obrigados a lutar até a morte! \nPara evitar que sua irmã seja a mais nova vítima do programa, Katniss se oferece para participar em seu lugar. Vinda do empobrecido Distrito 12, ela sabe como sobreviver em um ambiente hostil. Peeta, um garoto que ajudou sua família no passado, também foi selecionado. Caso vença, terá fama e fortuna. Se perder, morre. Mas para ganhar a competição, será preciso muito mais do que habilidade. Até onde Katniss estará disposta a ir para ser vitoriosa nos Jogos Vorazes? \nBest-seller da Veja, a trilogia Jogos Vorazes foi adaptada para o cinema e estrelada por Jennifer Lawrence.', 30.99, 'https://m.media-amazon.com/images/I/41XpauMr8ML._SY498_BO1,204,203,200_.jpg');
INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('Em Chamas', 'Suzanne Collins', 'Suspense', 403, 'Depois da improvável e inusitada vitória de Katniss Everdeen e Peeta Mellark nos últimos Jogos Vorazes, algo parece ter mudado para sempre em Panem. Aqui e ali, distúrbios e agitações nos distritos dão sinais de que uma revolta é iminente. Katniss e Peeta, representantes do paupérrimo Distrito 12, não apenas venceram os Jogos, mas ridicularizaram o governo e conseguiram fazer todos – incluindo o próprio Peeta – acreditarem que são um casal apaixonado. A confusão na cabeça de Katniss não é menor do que a das ruas. Em meio ao turbilhão, ela pensa cada vez mais em seu melhor amigo, o jovem caçador Gale, mas é obrigada a fingir que o romance com Peeta é real. Já o governo parece especialmente preocupado com a influência que os dois adolescente vitoriosos – transformados em verdadeiros ídolos nacionais – podem ter na população. Por isso, existem planos especiais para mantê-los sob controle, mesmo que isso signifique forçá-los a lutar novamente.', 28.40, 'https://m.media-amazon.com/images/I/51HSQRrpu3L.jpg');
INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('A Esperança', 'Suzanne Collins', 'Suspense', 424, 'Depois de sobreviver duas vezes à crueldade de uma arena projetada para destruí-la, Katniss acreditava que não precisaria mais lutar. Mas as regras do jogo mudaram: com a chegada dos rebeldes do lendário Distrito 13, enfim é possível organizar uma resistência. Começou a revolução. A coragem de Katniss nos jogos fez nascer a esperança em um país disposto a fazer de tudo para se livrar da opressão. E agora, contra a própria vontade, ela precisa assumir seu lugar como símbolo da causa rebelde. Ela precisa virar o Tordo. O sucesso da revolução dependerá de Katniss aceitar ou não essa responsabilidade. Será que vale a pena colocar sua família em risco novamente? Será que as vidas de Peeta e Gale serão os tributos exigidos nessa nova guerra? Acompanhe Katniss até o fim deste thriller, numa jornada ao lado mais obscuro da alma humana, em uma luta contra a opressão e a favor da esperança. Apenas um sobrevive. Best-seller da Veja, a trilogia Jogos Vorazes foi adaptada para o cinema e estrelada por Jennifer Lawrence.', 35.64, 'https://m.media-amazon.com/images/I/41tVioUwxLS._SY498_BO1,204,203,200_.jpg');
INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('O Impulso', 'Ashley Audrain', 'Suspense', 328, 'Blythe Connor está decidida a ser a mãe perfeita, calorosa e acolhedora que nunca teve. Porém, no começo exaustivo da maternidade, ela descobre que sua filha Violet não se comporta como a maioria das crianças. Ou ela estaria imaginando? Seu marido Fox está certo de que é tudo fruto do cansaço e que essa é apenas uma fase difícil. \nConforme seus medos são ignorados, Blythe começa a duvidar da própria sanidade. Mas quando nasce Sam, o segundo filho do casal, a experiência de Blythe é completamente diferente, e até Violet parece se dar bem com o irmãozinho. Bem no momento em que a vida parecia estar finalmente se ajustando, um grave acidente faz tudo sair dos trilhos, e Blythe é obrigada a confrontar a verdade. \nNeste eletrizante romance de estreia, Ashley Audrain escreve com maestria sobre o que os laços de família escondem e os dilemas invisíveis da maternidade, nos convidando a refletir: até onde precisamos ir para questionar aquilo em que acreditamos? \n“Muito original, O impulso é uma leitura compulsiva e um mergulho nos recantos mais escuros da maternidade.” ― Kristin Hannah, autora best-seller do New York Times', 28.90, 'https://m.media-amazon.com/images/I/51kvA2g-IvL._SX331_BO1,204,203,200_.jpg');
INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('It: A Coisa', 'Stephen King', 'Suspense', 1104, 'Durante as férias de 1958, em uma pacata cidadezinha chamada Derry, um grupo de sete amigos começa a ver coisas estranhas. Um conta que viu um palhaço, outro que viu uma múmia. Finalmente, acabam descobrindo que estavam todos vendo a mesma coisa: um ser sobrenatural e maligno que pode assumir várias formas. É assim que Bill, Beverly, Eddie, Ben, Richie, Mike e Stan enfrentam a Coisa pela primeira vez. \nQuase trinta anos depois, o grupo volta a se encontrar. Mike, o único que permaneceu em Derry, dá o sinal ― uma nova onda de terror tomou a pequena cidade. É preciso unir forças novamente. Só eles têm a chave do enigma. Só eles sabem o que se esconde nas entranhas de Derry. Só eles podem vencer a Coisa. \n“Mesmo depois de tantos anos, o público continua obcecado por IT. Ficamos obcecados porque todos temos medos. Todos temos algo que nos assusta, sejam palhaços e aranhas ou coisas que se escondem em um lugar muito mais profundo de nossa mente. Este livro fala com todo mundo. É o romance mais assustador de King, e duvido que isso vá mudar” ― The Guardian', 67.50, 'https://m.media-amazon.com/images/I/51z0s3GcvwL._SX346_BO1,204,203,200_.jpg');
INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('A Lista de Convidados', 'Lucy Foley', 'Suspense', 304, 'Em uma ilha afastada na costa da Irlanda, convidados se reúnem para celebrar uma união de dar inveja. O noivo, bonito e charmoso, é uma estrela de TV em ascensão. A noiva, elegante e ambiciosa, é editora da própria revista. A festa de casamento é um reflexo de suas personalidades: vestido e terno de grife, localização remota e exclusiva, decoração luxuosa, uísque da melhor qualidade. Tudo rigorosamente planejado. \nMas a perfeição só existe mesmo nos planos. E o perigo mora nos detalhes. À medida que as garrafas de champanhe estouram e a festa avança, o ressentimento e a inveja começam a se sobrepor à alegria e aos votos de felicidade. E então uma tempestade desaba com fúria sobre a ilha, e esse é só mais um motivo para abalar os ânimos já alterados. \nDepois de uma abrupta queda de luz no meio da festa, a garçonete anuncia aos convidados que um corpo foi encontrado. Isolados e aguardando a chegada da polícia, apenas uma coisa é certa: o assassino é uma das pessoas presentes no evento.', 39.90, 'https://m.media-amazon.com/images/I/41OpQ0473IL._SX379_BO1,204,203,200_.jpg');

INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('E Não Sobrou Nenhum', 'Agatha Christie', 'Mistério', 400, 'Uma ilha misteriosa, um poema infantil, dez soldadinhos de porcelana e muito suspense são os ingredientes com que Agatha Christie constrói seu romance mais importante. Na ilha do Soldado, antiga propriedade de um milionário norte-americano, dez pessoas sem nenhuma ligação aparente são confrontadas por uma voz misteriosa com fatos marcantes de seus passados. \nConvidados pelo misterioso mr. Owen, nenhum dos presentes tem muita certeza de por que estão ali, a despeito de conjecturas pouco convincentes que os leva a crer que passariam um agradável período de descanso em mordomia. Entretanto, já na primeira noite, o mistério e o suspense se abatem sobre eles e, num instante, todos são suspeitos, todos são vítimas e todos são culpados. \nÉ neste clima de tensão e desconforto que as mortes inexplicáveis começam e, sem comunicação com o continente devido a uma forte tempestade, a estadia transforma-se em um pesadelo. Todos se perguntam: quem é o misterioso anfitrião, mr. Owen? Existe mais alguém na ilha? O assassino pode ser um dos convidados? Que mente ardilosa teria preparado um crime tão complexo? E, sobretudo, por quê? \nSão essas e outras perguntas que o leitor será desafiado a resolver neste fabuloso romance de Agatha Christie, que envolve os espíritos mais perspicazes num complexo emaranhado de situações, lembranças e acusações na busca deste sagaz assassino. Medo, confinamento e angústia: que o leitor descubra por si mesmo porque E não sobrou nenhum foi eleito o melhor romance policial de todos os tempos.', 32.60, 'https://m.media-amazon.com/images/I/51zbr9-XvRS._SX331_BO1,204,203,200_.jpg');
INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('A Última Festa', 'Lucy Foley', 'Mistério', 304, 'Programado para acontecer em um cenário idílico, o réveillon que Miranda, Katie e os outros amigos que conheceram na faculdade passarão juntos este ano promete refeições deliciosas regadas a champanhe, música, jogos e conversas descontraídas. \nNo entanto, as tensões começam já na viagem de trem ― o grupo não tem mais nada em comum além de um passado de convivência, feridas jamais cicatrizadas e segredos potencialmente destrutivos. \nE então, em meio à grande festa da última noite do ano, o fio que os mantém unidos enfim arrebenta. No dia seguinte, alguém está morto e uma forte nevasca impede a vinda do resgate. Ninguém pode entrar. Ninguém pode sair. Nem o assassino. \nContada em flashbacks a partir das perspectivas dos vários personagens, a história deste malfadado encontro é um daqueles mistérios de assassinato cheio de tensão e de ritmo perfeito. Com uma trama assustadora e brilhantemente construída, A última festa planta no leitor a semente da dúvida: será que velhos amigos são sempre os melhores amigos?', 42.60, 'https://m.media-amazon.com/images/I/41EuVUbliHL._SX346_BO1,204,203,200_.jpg');
INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('Em Águas Profundas', 'F.T. Lukens', 'Mistério', 240, 'Reis, piratas e seres mágicos em um mundo de aventuras Tal é um jovem príncipe que viveu nas terras do reino de sua família. Ao longo dos anos, ele passou por um rigoroso treinamento para aprender a controlar a própria magia. Agora, aos 16, ele tem a oportunidade de realizar uma viagem ao lado do irmão mais velho, para explorar o reino e navegar por águas misteriosas, antes de assumir funções políticas oficiais. E a aventura começa quando ele é encarregado de vigiar um misterioso prisioneiro encontrado num barco abandonado. Tal se distrai com a forte conexão que logo estabelece com Athlen, que aproveita para fugir e desaparece em mar aberto. Ainda sem conseguir processar aqueles breves momentos, ele é sequestrado por piratas e mantido como refém para que revele seus poderes: algo que pode fazer explodir uma guerra e destruir toda a sua família. Uma narrativa repleta de magia, piratas, conflitos e intrigas reais! Em águas profundas despertará sua paixão por fantasia e personagens carismáticos com um romance como a espuma do mar. “Em águas profundas traz uma história deliciosa que mistura fantasia e romance de época. Comece pela aventura fantástica e seja fisgado pela paixão entre um príncipe e um pirata! Absolutamente divertido, do início ao fim.” – MACKENZIE LEE, autora best-seller de O guia do cavalheiro para o vício e a virtude', 22.99, 'https://m.media-amazon.com/images/I/51RdjiQfkVL._SX328_BO1,204,203,200_.jpg');
INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('Jantar Secreto', 'Raphael Montes', 'Mistério', 368, 'Um grupo de jovens deixa uma pequena cidade no Paraná para viver no Rio de Janeiro. Eles alugam um apartamento em Copacabana e fazem o possível para pagar a faculdade e manter vivos seus sonhos de sucesso na capital fluminense. Mas o dinheiro está curto e o aluguel está vencido. Para sair do buraco e manter o apartamento, os amigos adotam uma estratégia heterodoxa: arrecadar fundos por meio de jantares secretos, divulgados pela internet para uma clientela exclusiva da elite carioca. A partir daí, eles se envolvem em uma espiral de crimes, descobrem uma rede de contrabando de corpos, matadouros clandestinos e grã-finos excêntricos, e levam ao limite uma índole perversa que jamais imaginaram existir em cada um deles.', 44.10, 'https://m.media-amazon.com/images/I/41Ph9pr6j7L._SX334_BO1,204,203,200_.jpg');
INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('Matéria Escura', 'Blake Crouch', 'Mistério', 401, 'O fim de tudo que Jason Dessen conhece e ama começa em uma noite fria de outubro. É apenas uma saída casual para celebrar a conquista de um amigo no bar perto de casa. Ao se despedir da esposa e do filho, ele não olha para trás. \nPouco tempo depois, raptado por um homem mascarado, Jason é levado para uma usina abandonada e deixado inconsciente. Quando acorda, um estranho sorri para ele, dizendo: “Bem-vindo de volta, amigo.” \nNeste novo mundo, Jason leva outra vida. Sua esposa não é sua esposa, seu filho nunca nasceu e, em vez de professor numa universidade mediana, ele é um gênio da física quântica que conseguiu um feito inimaginável. Algo impossível. Será que é este seu mundo, e o outro é apenas um sonho? E, se esta não for a vida que ele sempre levou, como voltar para sua família e tudo que ele conhece por realidade? \nMarcante, veloz e intimista, Matéria escura retorna às livrarias em nova edição, nos levando a um universo muito maior do que imaginamos. Seus múltiplos cenários compõem uma trama que aborda questões profundamente humanas, como identidade, família, o peso das escolhas e até onde vamos para recuperar a vida com que sonhamos. O thriller sci-fi de Blake Crouch será adaptado para uma série do Apple TV+, em produção que contará com Alice Braga (Cidade de Deus) e Jennifer Connelly (Top Gun: Maverick).', 42.21, 'https://m.media-amazon.com/images/I/51w1jHLMlBL.jpg');
INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('A Garota do Lago', 'Charlie Donlea', 'Mistério', 296, 'Summit Lake, uma pequena cidade entre montanhas, é esse tipo de lugar, bucólico e com encantadoras casas dispostas à beira de um longo trecho de água intocada.Duas semanas atrás, a estudante de direito Becca Eckersley foi brutalmente assassinada em uma dessas casas. Filha de um poderoso advogado, Becca estava no auge de sua vida. Atraída instintivamente pela notícia, a repórter Kelsey Castle vai até a cidade para investigar o caso. ...E LOGO SE ESTABELECE UMA CONEXÃO ÍNTIMA QUANDO UM VIVO CAMINHA NAS MESMAS PEGADAS DOS MORTOS...E enquanto descobre sobre as amizades de Becca, sua vida amorosa e os segredos que ela guardava, a repórter fica cada vez mais convencida de que a verdade sobre o que aconteceu com Becca pode ser a chave para superar as marcas sombrias de seu próprio passado.', 11.99, 'https://m.media-amazon.com/images/I/516VOgxwg2L._SX339_BO1,204,203,200_.jpg');

-- INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('', '', '', , '', ., '');
-- INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('', '', '', , '', ., '');
-- INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('', '', '', , '', ., '');
-- INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('', '', '', , '', ., '');
-- INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('', '', '', , '', ., '');
-- INSERT INTO tb_books (title, author, genre, num_pags, info, book_value, img_url) VALUES ('', '', '', , '', ., '');



INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (2, 1, 1);
INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (3, 1, 2);
INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (4, 1, 3);
INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (5, 1, 4);
INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (6, 1, 5);

INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (7, 2, 0);
INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (8, 2, 1);
INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (9, 2, 2);
INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (10, 2, 3);
INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (11, 2, 4);
INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (12, 2, 5);

INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (13, 3, 0);
INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (14, 3, 1);
INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (15, 3, 2);
INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (16, 3, 3);
INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (17, 3, 4);
INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (18, 3, 5);

INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (19, 4, 0);
INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (20, 4, 1);
INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (21, 4, 2);
INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (22, 4, 3);
INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (23, 4, 4);
INSERT INTO tb_belonging (book_id, shelve_id, position) VALUES (24, 4, 5);
